version: 2
jobs:
  build_dev:
    docker:
      - image: node:10
    working_directory: /home/ubuntu/ds-sdk
    steps:
      - checkout
      - run: npm install
      
      - run: npm run build:all
      
      - run: apt-get update
      - run: apt-get -qq install python-pip python-dev jq yui-compressor
      - run: pip install awscli
      - run: yui-compressor bundels/dialogshift-webchat-sdk.umd.js
      - run: mkdir sdk
      - run: mkdir sdk/$(jq -r '.version' package.json)
      - run: cp bundles/* sdk/$(jq -r '.version' package.json)
      - run: aws s3 sync sdk s3://webchat.dev.co25.net/sdk --region eu-central-1

workflows:
  version: 2

  sa_build_deploy:
    jobs:
      - build_dev:
          filters:
            branches:
              only: develop