version: 2
jobs:
  build_prodx:
    docker:
      - image: node:10
    working_directory: /home/ubuntu/ds-sdk
    steps:
      - checkout
      - run: npm install
      
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
      

      - run: apt-get update
      - run: apt-get -qq install python-pip python-dev jq
      - run: pip install awscli
      - run: mkdir sdk
      - run: cp bundles/* sdk/$(jq '.version' package.json)
      - run: aws s3 sync sdk s3://webchat.dev.co25.net/sdk --region eu-central-1

workflows:
  version: 2

  sa_build_deploy:
    jobs:
      - build_prod:
          filters:
            branches:
              only: master